[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements-ultra-minimal.txt']

[phases.build]
cmds = ['echo "Ultra minimal build completed"']

[start]
cmd = 'python3 ultra_minimal_app.py' 